package com.lyxr.IDao;

import com.lyxr.domain.JuduiChat;

public interface JuduiChatMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table judui_chat
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table judui_chat
     *
     * @mbggenerated
     */
    int insert(JuduiChat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table judui_chat
     *
     * @mbggenerated
     */
    int insertSelective(JuduiChat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table judui_chat
     *
     * @mbggenerated
     */
    JuduiChat selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table judui_chat
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(JuduiChat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table judui_chat
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(JuduiChat record);
}