package com.lyxr.IDao;

import com.lyxr.domain.JuduiPhone;

public interface JuduiPhoneMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table judui_phone
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table judui_phone
     *
     * @mbggenerated
     */
    int insert(JuduiPhone record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table judui_phone
     *
     * @mbggenerated
     */
    int insertSelective(JuduiPhone record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table judui_phone
     *
     * @mbggenerated
     */
    JuduiPhone selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table judui_phone
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(JuduiPhone record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table judui_phone
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(JuduiPhone record);
}