package com.lyxr.IDao;

import com.lyxr.domain.JuduiTask;

public interface JuduiTaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table judui_task
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table judui_task
     *
     * @mbggenerated
     */
    int insert(JuduiTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table judui_task
     *
     * @mbggenerated
     */
    int insertSelective(JuduiTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table judui_task
     *
     * @mbggenerated
     */
    JuduiTask selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table judui_task
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(JuduiTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table judui_task
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(JuduiTask record);
}