package com.lyxr.IDao;

import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;

import com.lyxr.domain.JuduiUser;

public interface JuduiUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table judui_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table judui_user
     *
     * @mbggenerated
     */
    int insert(JuduiUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table judui_user
     *
     * @mbggenerated
     */
    int insertSelective(JuduiUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table judui_user
     *
     * @mbggenerated
     */
    JuduiUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table judui_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(JuduiUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table judui_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(JuduiUser record);
    
    @Select("select * from judui_user where account = #{0} and password = #{1};")
    @ResultMap("BaseResultMap")
    JuduiUser islogin(String username,String password);
}