package com.lyxr.IDao;

import com.lyxr.domain.JuduiGroup;

public interface JuduiGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table judui_group
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table judui_group
     *
     * @mbggenerated
     */
    int insert(JuduiGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table judui_group
     *
     * @mbggenerated
     */
    int insertSelective(JuduiGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table judui_group
     *
     * @mbggenerated
     */
    JuduiGroup selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table judui_group
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(JuduiGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table judui_group
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(JuduiGroup record);
}