package com.lyxr.domain;

import java.util.Date;

public class JuduiTask {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column judui_task.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column judui_task.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column judui_task.detail
     *
     * @mbggenerated
     */
    private String detail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column judui_task.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column judui_task.gid
     *
     * @mbggenerated
     */
    private Integer gid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column judui_task.price
     *
     * @mbggenerated
     */
    private Double price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column judui_task.date
     *
     * @mbggenerated
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column judui_task.cycle
     *
     * @mbggenerated
     */
    private Integer cycle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column judui_task.score
     *
     * @mbggenerated
     */
    private Integer score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column judui_task.isuse
     *
     * @mbggenerated
     */
    private Integer isuse;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column judui_task.id
     *
     * @return the value of judui_task.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column judui_task.id
     *
     * @param id the value for judui_task.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column judui_task.name
     *
     * @return the value of judui_task.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column judui_task.name
     *
     * @param name the value for judui_task.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column judui_task.detail
     *
     * @return the value of judui_task.detail
     *
     * @mbggenerated
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column judui_task.detail
     *
     * @param detail the value for judui_task.detail
     *
     * @mbggenerated
     */
    public void setDetail(String detail) {
        this.detail = detail == null ? null : detail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column judui_task.remark
     *
     * @return the value of judui_task.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column judui_task.remark
     *
     * @param remark the value for judui_task.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column judui_task.gid
     *
     * @return the value of judui_task.gid
     *
     * @mbggenerated
     */
    public Integer getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column judui_task.gid
     *
     * @param gid the value for judui_task.gid
     *
     * @mbggenerated
     */
    public void setGid(Integer gid) {
        this.gid = gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column judui_task.price
     *
     * @return the value of judui_task.price
     *
     * @mbggenerated
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column judui_task.price
     *
     * @param price the value for judui_task.price
     *
     * @mbggenerated
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column judui_task.date
     *
     * @return the value of judui_task.date
     *
     * @mbggenerated
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column judui_task.date
     *
     * @param date the value for judui_task.date
     *
     * @mbggenerated
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column judui_task.cycle
     *
     * @return the value of judui_task.cycle
     *
     * @mbggenerated
     */
    public Integer getCycle() {
        return cycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column judui_task.cycle
     *
     * @param cycle the value for judui_task.cycle
     *
     * @mbggenerated
     */
    public void setCycle(Integer cycle) {
        this.cycle = cycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column judui_task.score
     *
     * @return the value of judui_task.score
     *
     * @mbggenerated
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column judui_task.score
     *
     * @param score the value for judui_task.score
     *
     * @mbggenerated
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column judui_task.isuse
     *
     * @return the value of judui_task.isuse
     *
     * @mbggenerated
     */
    public Integer getIsuse() {
        return isuse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column judui_task.isuse
     *
     * @param isuse the value for judui_task.isuse
     *
     * @mbggenerated
     */
    public void setIsuse(Integer isuse) {
        this.isuse = isuse;
    }
}