package com.lyxr.domain;

public class JuduiPhone {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column judui_phone.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column judui_phone.phoneid
     *
     * @mbggenerated
     */
    private String phoneid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column judui_phone.uid
     *
     * @mbggenerated
     */
    private Integer uid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column judui_phone.id
     *
     * @return the value of judui_phone.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column judui_phone.id
     *
     * @param id the value for judui_phone.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column judui_phone.phoneid
     *
     * @return the value of judui_phone.phoneid
     *
     * @mbggenerated
     */
    public String getPhoneid() {
        return phoneid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column judui_phone.phoneid
     *
     * @param phoneid the value for judui_phone.phoneid
     *
     * @mbggenerated
     */
    public void setPhoneid(String phoneid) {
        this.phoneid = phoneid == null ? null : phoneid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column judui_phone.uid
     *
     * @return the value of judui_phone.uid
     *
     * @mbggenerated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column judui_phone.uid
     *
     * @param uid the value for judui_phone.uid
     *
     * @mbggenerated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }
}