package com.lyxr.domain;

import java.util.Date;

public class JuduiGroupUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column judui_group_user.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column judui_group_user.gid
     *
     * @mbggenerated
     */
    private Integer gid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column judui_group_user.uid
     *
     * @mbggenerated
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column judui_group_user.joindate
     *
     * @mbggenerated
     */
    private Date joindate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column judui_group_user.isadmin
     *
     * @mbggenerated
     */
    private Integer isadmin;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column judui_group_user.id
     *
     * @return the value of judui_group_user.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column judui_group_user.id
     *
     * @param id the value for judui_group_user.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column judui_group_user.gid
     *
     * @return the value of judui_group_user.gid
     *
     * @mbggenerated
     */
    public Integer getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column judui_group_user.gid
     *
     * @param gid the value for judui_group_user.gid
     *
     * @mbggenerated
     */
    public void setGid(Integer gid) {
        this.gid = gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column judui_group_user.uid
     *
     * @return the value of judui_group_user.uid
     *
     * @mbggenerated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column judui_group_user.uid
     *
     * @param uid the value for judui_group_user.uid
     *
     * @mbggenerated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column judui_group_user.joindate
     *
     * @return the value of judui_group_user.joindate
     *
     * @mbggenerated
     */
    public Date getJoindate() {
        return joindate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column judui_group_user.joindate
     *
     * @param joindate the value for judui_group_user.joindate
     *
     * @mbggenerated
     */
    public void setJoindate(Date joindate) {
        this.joindate = joindate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column judui_group_user.isadmin
     *
     * @return the value of judui_group_user.isadmin
     *
     * @mbggenerated
     */
    public Integer getIsadmin() {
        return isadmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column judui_group_user.isadmin
     *
     * @param isadmin the value for judui_group_user.isadmin
     *
     * @mbggenerated
     */
    public void setIsadmin(Integer isadmin) {
        this.isadmin = isadmin;
    }
}