package com.lyxr.domain;

public class JuduiLogin {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column judui_login.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column judui_login.uid
     *
     * @mbggenerated
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column judui_login.logindate
     *
     * @mbggenerated
     */
    private String logindate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column judui_login.loginip
     *
     * @mbggenerated
     */
    private String loginip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column judui_login.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column judui_login.login_position
     *
     * @mbggenerated
     */
    private String loginPosition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column judui_login.phone_id
     *
     * @mbggenerated
     */
    private Integer phoneId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column judui_login.id
     *
     * @return the value of judui_login.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column judui_login.id
     *
     * @param id the value for judui_login.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column judui_login.uid
     *
     * @return the value of judui_login.uid
     *
     * @mbggenerated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column judui_login.uid
     *
     * @param uid the value for judui_login.uid
     *
     * @mbggenerated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column judui_login.logindate
     *
     * @return the value of judui_login.logindate
     *
     * @mbggenerated
     */
    public String getLogindate() {
        return logindate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column judui_login.logindate
     *
     * @param logindate the value for judui_login.logindate
     *
     * @mbggenerated
     */
    public void setLogindate(String logindate) {
        this.logindate = logindate == null ? null : logindate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column judui_login.loginip
     *
     * @return the value of judui_login.loginip
     *
     * @mbggenerated
     */
    public String getLoginip() {
        return loginip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column judui_login.loginip
     *
     * @param loginip the value for judui_login.loginip
     *
     * @mbggenerated
     */
    public void setLoginip(String loginip) {
        this.loginip = loginip == null ? null : loginip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column judui_login.remark
     *
     * @return the value of judui_login.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column judui_login.remark
     *
     * @param remark the value for judui_login.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column judui_login.login_position
     *
     * @return the value of judui_login.login_position
     *
     * @mbggenerated
     */
    public String getLoginPosition() {
        return loginPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column judui_login.login_position
     *
     * @param loginPosition the value for judui_login.login_position
     *
     * @mbggenerated
     */
    public void setLoginPosition(String loginPosition) {
        this.loginPosition = loginPosition == null ? null : loginPosition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column judui_login.phone_id
     *
     * @return the value of judui_login.phone_id
     *
     * @mbggenerated
     */
    public Integer getPhoneId() {
        return phoneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column judui_login.phone_id
     *
     * @param phoneId the value for judui_login.phone_id
     *
     * @mbggenerated
     */
    public void setPhoneId(Integer phoneId) {
        this.phoneId = phoneId;
    }
}